/**
 * AI Provider Configurations
 * Supports OpenAI-compatible, Anthropic, and Gemini API formats
 */

export const AI_PROVIDERS = [
  {
    id: 'openai',
    name: 'OpenAI',
    icon: '🤖',
    format: 'openai',
    defaultBaseUrl: 'https://api.openai.com/v1',
    models: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo', 'gpt-3.5-turbo'],
    defaultModel: 'gpt-4o-mini',
    keyPlaceholder: 'sk-...',
    docsUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'anthropic',
    name: 'Anthropic (Claude)',
    icon: '🧠',
    format: 'anthropic',
    defaultBaseUrl: 'https://api.anthropic.com/v1',
    models: ['claude-3-5-sonnet-20241022', 'claude-3-5-haiku-20241022', 'claude-3-opus-20240229'],
    defaultModel: 'claude-3-5-sonnet-20241022',
    keyPlaceholder: 'sk-ant-...',
    docsUrl: 'https://console.anthropic.com/settings/keys',
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    icon: '✨',
    format: 'gemini',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    models: ['gemini-2.0-flash', 'gemini-1.5-pro', 'gemini-1.5-flash'],
    defaultModel: 'gemini-2.0-flash',
    keyPlaceholder: 'AIza...',
    docsUrl: 'https://aistudio.google.com/app/apikey',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    icon: '🌪️',
    format: 'openai',
    defaultBaseUrl: 'https://api.mistral.ai/v1',
    models: ['mistral-large-latest', 'mistral-medium-latest', 'mistral-small-latest', 'open-mistral-7b'],
    defaultModel: 'mistral-large-latest',
    keyPlaceholder: '...',
    docsUrl: 'https://console.mistral.ai/api-keys/',
  },
  {
    id: 'groq',
    name: 'Groq',
    icon: '⚡',
    format: 'openai',
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768'],
    defaultModel: 'llama-3.3-70b-versatile',
    keyPlaceholder: 'gsk_...',
    docsUrl: 'https://console.groq.com/keys',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    icon: '🔮',
    format: 'openai',
    defaultBaseUrl: 'https://api.deepseek.com/v1',
    models: ['deepseek-chat', 'deepseek-reasoner'],
    defaultModel: 'deepseek-chat',
    keyPlaceholder: 'sk-...',
    docsUrl: 'https://platform.deepseek.com/api_keys',
  },
  {
    id: 'together',
    name: 'Together AI',
    icon: '🤝',
    format: 'openai',
    defaultBaseUrl: 'https://api.together.xyz/v1',
    models: ['meta-llama/Llama-3.3-70B-Instruct-Turbo', 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo', 'Qwen/Qwen2.5-72B-Instruct-Turbo'],
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    keyPlaceholder: '...',
    docsUrl: 'https://api.together.ai/settings/api-keys',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    icon: '🌐',
    format: 'openai',
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    models: ['openai/gpt-4o-mini', 'anthropic/claude-3.5-sonnet', 'google/gemini-2.0-flash-exp:free', 'meta-llama/llama-3.3-70b-instruct:free'],
    defaultModel: 'openai/gpt-4o-mini',
    keyPlaceholder: 'sk-or-...',
    docsUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    icon: '🔍',
    format: 'openai',
    defaultBaseUrl: 'https://api.perplexity.ai',
    models: ['llama-3.1-sonar-large-128k-online', 'llama-3.1-sonar-small-128k-online'],
    defaultModel: 'llama-3.1-sonar-large-128k-online',
    keyPlaceholder: 'pplx-...',
    docsUrl: 'https://docs.perplexity.ai/guides/getting-started',
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    icon: '𝕏',
    format: 'openai',
    defaultBaseUrl: 'https://api.x.ai/v1',
    models: ['grok-2-1212', 'grok-2-vision-1212', 'grok-beta'],
    defaultModel: 'grok-2-1212',
    keyPlaceholder: 'xai-...',
    docsUrl: 'https://console.x.ai/',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    icon: '🔗',
    format: 'cohere',
    defaultBaseUrl: 'https://api.cohere.com/v1',
    models: ['command-r-plus-08-2024', 'command-r-08-2024', 'command-r7b-12-2024'],
    defaultModel: 'command-r-plus-08-2024',
    keyPlaceholder: '...',
    docsUrl: 'https://dashboard.cohere.com/api-keys',
  },
  {
    id: 'ollama',
    name: 'Ollama (Local)',
    icon: '🦙',
    format: 'openai',
    defaultBaseUrl: 'http://localhost:11434/v1',
    models: ['llama3.3', 'qwen2.5', 'mistral', 'phi3'],
    defaultModel: 'llama3.3',
    keyPlaceholder: 'ollama',
    docsUrl: 'https://ollama.com/download',
  },
  {
    id: 'custom',
    name: 'Custom Provider',
    icon: '⚙️',
    format: 'openai',
    defaultBaseUrl: '',
    models: [],
    defaultModel: '',
    keyPlaceholder: 'your-api-key',
    docsUrl: '',
  },
]

export const DEFAULT_PROVIDER = AI_PROVIDERS[0]
